"""Compile a minimal movement context pack (kernel + on-scene state)."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from . import card_io, ledger_io, logs_io, yaml_util
from .paths import BUILD_CONTEXT, KERNEL, REALM_DATA, rel

# Bias catalog (compact) — keep in sync with Main.md table
BIAS_RULES: dict[str, dict[str, str]] = {
    "Debt Ledger": {
        "trigger": "Safety, affection, rest",
        "rewrite": "Relief = payment on infinite unpayable debt",
        "hearing": "Kindness = bill due",
        "somatic": "Tight throat, high shoulders, jaw lock",
    },
    "Saviour Complex": {
        "trigger": "Another's pain or need",
        "rewrite": "Merge/fix = love",
        "hearing": "Need = assignment",
        "somatic": "Soft chest, open hands, sudden inhale",
    },
    "System Architect": {
        "trigger": "Emotion, chaos, intimacy",
        "rewrite": "Feeling = design constraint",
        "hearing": "Vulnerability = load problem",
        "somatic": "Still posture, folded hands",
    },
    "Mirror": {
        "trigger": "Collision, strong want",
        "rewrite": "Suppress want; reflect other",
        "hearing": "Desire = vanish into",
        "somatic": "Stillness, loose jaw",
    },
    "Insulation": {
        "trigger": "Pressure on the bond",
        "rewrite": "Structure = shield for us",
        "hearing": "Outside = threat to bond",
        "somatic": "Warm touch, face-scan",
    },
    "Dissolution": {
        "trigger": "Edge/performance fear",
        "rewrite": "Exit the performed self",
        "hearing": "Invitation = disappear",
        "somatic": "Lilt, tremor, shallow breath",
    },
}


def _bias_key(cognitive_bias: str) -> str | None:
    for name in BIAS_RULES:
        if name.lower() in cognitive_bias.lower():
            return name
    # first segment before em dash
    head = re.split(r"[—-]", cognitive_bias, maxsplit=1)[0].strip()
    for name in BIAS_RULES:
        if name.lower() == head.lower():
            return name
    return None


def _load_realms(keys: list[str]) -> dict[str, Any]:
    if not REALM_DATA.is_file():
        return {}
    raw = yaml_util.load_file(REALM_DATA)
    realms = (raw or {}).get("realms") or {}
    out: dict[str, Any] = {}
    for k in keys:
        if k in realms:
            out[k] = realms[k]
    return out


def _history_slice(history: list, tier: str) -> list:
    if not history:
        return []
    if tier == "red":
        return []
    if tier == "yellow":
        return history[-3:]
    return history[-8:]


def build_pack(
    *,
    slugs: list[str],
    brief: str = "",
    tier: str = "yellow",
    include_preceding: Path | None = None,
) -> str:
    tier = tier.lower().strip()
    if tier not in ("green", "yellow", "red"):
        tier = "yellow"

    cards = card_io.load_cards(slugs)
    logs = logs_io.load_all_logs()
    rows = ledger_io.parse_ledger()
    latest = rows[-3:] if rows else []

    kernel = KERNEL.read_text(encoding="utf-8") if KERNEL.is_file() else "# Kernel missing\n"

    realm_keys: list[str] = []
    for c in cards:
        for k in c.realm_keys():
            if k not in realm_keys:
                realm_keys.append(k)
        # also from log snapshot focus
        log = logs.get(c.slug) or logs.get(c.slug.lower())
        if log:
            focus = str((log.get("snapshot") or {}).get("active_focus") or "")
            for m in re.finditer(r"\b(I|II|III|IV|V|VI|VII|VIII|IX|X)\b", focus):
                if m.group(1) not in realm_keys:
                    realm_keys.append(m.group(1))

    realms = _load_realms(realm_keys) if tier != "red" or realm_keys else _load_realms(realm_keys)

    parts: list[str] = [
        "# Movement context pack",
        f"*Generated by midlayer pack · tier={tier} · cast={', '.join(slugs)}*",
        "",
        "Do not load full Main.md / full realm catalog unless designing. This pack is sufficient to draft.",
        "",
        "---",
        "",
        kernel.strip(),
        "",
        "---",
        "",
        "## Movement brief",
        "",
        brief.strip() if brief.strip() else "*(no brief text provided — paste author brief here)*",
        "",
        "---",
        "",
        "## Continuity (latest ledger rows)",
        "",
    ]

    if not latest:
        parts.append("*(no committed movements yet — honest empty)*")
    else:
        parts.append("| Ch/Mov | Draft | Day & Time | Somatic close | Beats |")
        parts.append("| :--- | :--- | :--- | :--- | :--- |")
        for r in latest:
            parts.append(
                f"| {r.ch_mov} | {r.draft_file} | {r.day_time} | {r.somatic} | {r.beats} |"
            )
    parts.append("")

    parts.extend(["---", "", "## On-scene characters", ""])

    for card in cards:
        log = logs.get(card.slug) or {}
        snap = (log.get("snapshot") if log else None) or {}
        parts.append(f"### {card.name} (`{card.slug}`)")
        parts.append("")
        parts.append("#### Identity (card)")
        parts.append(f"- **physical:** {card.meta.get('physical', '')}")
        parts.append(f"- **cultural_bias:** {card.meta.get('cultural_bias', '')}")
        parts.append(f"- **cognitive_bias:** {card.cognitive_bias}")
        parts.append(f"- **voice:** {card.meta.get('voice', {})}")
        parts.append(f"- **history_anchors:** {card.meta.get('history_anchors', [])}")
        parts.append(f"- **canon_adult:** {card.meta.get('canon_adult', '')}")
        parts.append("")
        parts.append("#### Runtime snapshot (log overrides card)")
        if snap:
            parts.append("```yaml")
            parts.append(yaml_util.dump({"snapshot": snap, "skills": log.get("skills"), "memories": log.get("memories"), "temporary_effects": log.get("temporary_effects")}).rstrip())
            parts.append("```")
        else:
            parts.append("*(no log — using card defaults only; seed a log before commit)*")
            parts.append(f"- build focus: {card.active_focus}")
            parts.append(f"- build somatic: {card.default_somatic}")
        parts.append("")
        hist = _history_slice(list(log.get("history") or []), tier)
        if hist:
            parts.append("#### Recent history")
            parts.append("```yaml")
            parts.append(yaml_util.dump(hist).rstrip())
            parts.append("```")
            parts.append("")

        bkey = _bias_key(card.cognitive_bias)
        if bkey:
            rule = BIAS_RULES[bkey]
            parts.append(f"#### Compiled bias rule — {bkey} (off-page)")
            parts.append(f"- trigger: {rule['trigger']}")
            parts.append(f"- rewrite: {rule['rewrite']}")
            parts.append(f"- hearing warp: {rule['hearing']}")
            parts.append(f"- somatic: {rule['somatic']}")
            parts.append("")

    if realms:
        parts.extend(["---", "", "## Realm somatics (on-scene only)", "", "```yaml"])
        parts.append(yaml_util.dump({"realms": realms}).rstrip())
        parts.append("```")
        parts.append("")

    if include_preceding and include_preceding.is_file():
        text = include_preceding.read_text(encoding="utf-8")
        if tier == "red":
            paras = [p for p in re.split(r"\n\s*\n", text) if p.strip()]
            text = "\n\n".join(paras[-5:])
            parts.extend(
                [
                    "---",
                    "",
                    f"## Preceding prose (last 5 paragraphs) — {rel(include_preceding)}",
                    "",
                    text,
                    "",
                ]
            )
        else:
            parts.extend(
                [
                    "---",
                    "",
                    f"## Preceding prose — {rel(include_preceding)}",
                    "",
                    text,
                    "",
                ]
            )

    parts.extend(
        [
            "---",
            "",
            "## After approval",
            "",
            "```bash",
            "python3 scripts/run.py midlayer commit \\",
            f"  --movement \"N M#\" --draft Drafts/draft_chapter_N_mM.md \\",
            f"  --slugs {','.join(slugs)} --day \"…\" --somatic \"…\" --beats \"…\" \\",
            "  --pressure Emotional/Social --strength Medium",
            "python3 scripts/run.py midlayer status",
            "```",
            "",
        ]
    )
    return "\n".join(parts)


def write_pack(content: str, out: Path | None = None) -> Path:
    out = out or (BUILD_CONTEXT / "movement_pack.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    return out
